### ISSUE TITLE
Prepare project repository for submission.

### ISSUE THREAD

**Issue by KirylowE** [KirylowE/NewBankGroup5#53]
The following steps needs to be taken before a repository is made available:

- [x] Make GitHub repository public
- [x] Make Trello boards public
- [x] Get links to Metro retro boards
- [x] Get link of the Microsoft Teams chat 
- [x] Add links to Wiki

**Comment by ardallie** [comment]
Completed.

**Comment by ardallie** [comment]
Reopened for review.
